### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by webalexeu**

### CODE REVIEW

**Comment by sathieu** [comment]
This project is dead (I no longer use Puppet).

Can you make a PR pointing to your fork?

**Comment by webalexeu** [comment]
Hello,

I was preparing a new release but wondering if you prefer that I send you a PR or if you prefer that I create a new module as you don't use puppet anymore?

Thank you for your quick reply

**Comment by sathieu** [comment]
I prefer that you create a new module.

The PR would be to add a link to your module.

**Comment by webalexeu** [comment]
Here is the link of the new module
https://github.com/webalexeu/puppet-winhttp_proxy

Let me know if you want me to create the PR on your end to add the link ?

**Comment by sathieu** [comment]
done https://github.com/sathieu/puppet-winhttp_proxy/commit/fd9edc3aee9036c94504bee03fe6532a8f346efa

**Pull request closed without merging**
